# Cross Referencing and Citatians {#chapter4}

Cross-references make it easier for readers to find and link to elements in your book. In Bookdown, you can create cross-references for sections, figures, tables, and equations. This chapter explains how to use cross-references effectively.

---

## Cross-Referencing Sections

To reference a section, first add an ID or tag to the heading by including `{#your-id}` at the end of the section header. As an example here is the last chapter of the book that is an analysis I created within bookdown set as a single chapter:

```markdown
# Example Document: Union Earnings Analysis (#examplepaper)
```

You can then refer to it later, with a clickable link that will take your reader directly to it, in your document as follows:

```markdown
See Section \@ref(examplepaper) for more information.
```
See Section \@ref(examplepaper) for more information.
---

## Cross-Referencing Text

You can assign some text to a label and reference the text using the label elsewhere in your document. This can be particularly useful for long figure/table captions or when you need to reuse text fragments in multiple places.

The syntax for a text reference is `(ref:label) text`, where `label` is a unique label throughout the document. It must be in a separate paragraph with empty lines above and below it. The paragraph must not be wrapped into multiple lines, and should not end with whitespace.

**Additional Guidelines**:
- Ensure that text references are in a separate paragraph with empty lines above and below.
- Avoid wrapping the paragraph containing the text reference into multiple lines.
- Make sure there is no trailing whitespace at the end of the paragraph.

Example:

~~~
(ref:textreference) This is the text we are referencing
~~~
(ref:textreference) This is the text we are referencing

Then you can reference this text in your document using `(ref:textreference)`.

For example:

Then we reference it: 
(ref:textreference).

---

## Cross-Referencing Figures

To cross-reference a figure, set a chunk label and use the `fig.cap` option to add a caption. Bookdown automatically labels the figure with `fig:chunk-label`.

For example in the previous chapter we showed a plot comparing Union Wages vs Non-Union Wages. It had the following in the code chunk heading:

`{r wagecomparison, fig.cap="Union Vs Non-Union Wages"}`

We can easily create a reference back to this plot, that is clickable so users can easily go back to it, with the following: 

```markdown
See Figure \@ref(fig:wagecomparison) for details.
```
See Figure \@ref(fig:wagecomparison) for details.

---

## Cross-Referencing Tables

To cross-reference a table, use `knitr::kable()` to create a table with a caption. Bookdown automatically labels the table with `tab:chunk-label`.

Example:

```{r cars-table}
knitr::kable(head(cars), caption = "Table of the first rows of the cars dataset")
```

Reference this table using:

```markdown
See Table \@ref(tab:cars-table) for details.
```
See Table \@ref(tab:cars-table) for details.

---

## Cross-Referencing Equations

For equations, use `(\#eq:label)` to label the equation and `\@ref(eq:label)` to reference it. This way when you need to reference the equation at a later point in your document you can.

### Example: Creating and Labeling an Equation
First you write the equation in LaTeX in the equation environment and include the label as `(\#eq:label)`:


```markdown
\begin{equation}
  E = mc^2
  (\#eq:einstein)
\end{equation}
```

Which outputs as such:

\begin{equation}
  E = mc^2
  (\#eq:einstein)
\end{equation}

Then at a later point when you need to reference it you simply type in `\@ref(eq:label)`. As we know Einsten discovered that \@ref(eq:einstein).

## Adding Citations and Managing References

Bookdown makes it easy to manage references and add citations by using BibTeX files. Here’s how to set up and include references in your Bookdown project.

### Step 1: Create a `.bib` File

First, create a `.bib` file for your references (e.g., `references.bib`). You can add references in BibTeX format. Here’s an example entry:

```bibtex
@Book{Bookdown,
  title     = {Bookdown: Authoring Books and Technical Documents with R Markdown},
  author    = {Yihui Xie},
  publisher = {Chapman; Hall/CRC},
  year      = 2024,
  edition   = {2nd},
  note      = {ISBN 9780367142568},
  url       = {https://bookdown.org/yihui/bookdown/}
}
```

### Step 2: Link the `.bib` File in `index.Rmd`

In your `index.Rmd` file, include the `.bib` file in the YAML header:

```markdown
bibliography: [references.bib]
link-citations: yes
```


### Step 3: Cite Sources in Your Text

To cite a source, use `[@citation-key]` in your text, where `citation-key` matches the key in your `.bib` file (e.g., `[@Bookdown]`). For example:

```markdown
This tutorial was written thanks to Bookdown [@Bookdown].
```

This tutorial was written thanks to Bookdown [@Bookdown].

Bookdown will automatically format your citation based on the output style.

### Step 4: Customize Citation Style (Optional)

If you need a specific citation style, you can add a `.csl` (Citation Style Language) file in your project and reference it in the YAML header:

```markdown
csl: "chicago-author-date.csl"
```

Download `.csl` files from sources like [Zotero](https://www.zotero.org/styles).

## Using Cross-References with Citations

In addition to referencing external sources, Bookdown allows you to cross-reference sections, figures, and tables, as discussed earlier. As a reminder:

```markdown
As shown in Figure \@ref(fig:example-figure), the trend is evident.
```

Using cross-references with citations helps keep your document organized and easy to navigate.
---
:::: {.blackbox data-latex=""}
::: {.center data-latex=""}
**EXERCISE TIME!**
:::
Go ahead and place a few entries in your .bib file. Once you've done that go through and reference these in your previously written content.
::::